# Generated by Django 6.0.3 on 2026-03-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "verbose_name": "Promo code",
                "verbose_name_plural": "Promo codes",
            },
        ),
        migrations.AlterModelOptions(
            name="promocodeusage",
            options={
                "verbose_name": "Promo code usage",
                "verbose_name_plural": "Promo code usages",
            },
        ),
    ]
